# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ARGAZAL_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/ARGAZAL_package.proto\x12\x0f\x41RGAZAL_package\"\xf6\x03\n\x17\x41RGAZAL_package_message\x12\x10\n\x08z1ufp_nw\x18\x01 \x01(\x02\x12\x0f\n\x07z1bc_nw\x18\x02 \x01(\x02\x12\x10\n\x08z1no2_nw\x18\x03 \x01(\x02\x12\x10\n\x08z1ufp_ew\x18\x04 \x01(\x02\x12\x0f\n\x07z1bc_ew\x18\x05 \x01(\x02\x12\x10\n\x08z1no2_ew\x18\x06 \x01(\x02\x12\x10\n\x08z1ufp_sw\x18\x07 \x01(\x02\x12\x0f\n\x07z1bc_sw\x18\x08 \x01(\x02\x12\x10\n\x08z1no2_sw\x18\t \x01(\x02\x12\x10\n\x08z2ufp_nw\x18\n \x01(\x02\x12\x0f\n\x07z2bc_nw\x18\x0b \x01(\x02\x12\x10\n\x08z2no2_nw\x18\x0c \x01(\x02\x12\x10\n\x08z2ufp_ew\x18\r \x01(\x02\x12\x0f\n\x07z2bc_ew\x18\x0e \x01(\x02\x12\x10\n\x08z2no2_ew\x18\x0f \x01(\x02\x12\x10\n\x08z2ufp_sw\x18\x10 \x01(\x02\x12\x0f\n\x07z2bc_sw\x18\x11 \x01(\x02\x12\x10\n\x08z2no2_sw\x18\x12 \x01(\x02\x12\x10\n\x08z3ufp_nw\x18\x13 \x01(\x02\x12\x0f\n\x07z3bc_nw\x18\x14 \x01(\x02\x12\x10\n\x08z3no2_nw\x18\x15 \x01(\x02\x12\x10\n\x08z3ufp_ew\x18\x16 \x01(\x02\x12\x0f\n\x07z3bc_ew\x18\x17 \x01(\x02\x12\x10\n\x08z3no2_ew\x18\x18 \x01(\x02\x12\x10\n\x08z3ufp_sw\x18\x19 \x01(\x02\x12\x0f\n\x07z3bc_sw\x18\x1a \x01(\x02\x12\x10\n\x08z3no2_sw\x18\x1b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.ARGAZAL_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARGAZAL_PACKAGE_MESSAGE']._serialized_start=50
  _globals['_ARGAZAL_PACKAGE_MESSAGE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
