# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ASCCDCV_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/ASCCDCV_package.proto\x12\x0f\x41SCCDCV_package\"\xd8\x01\n\x17\x41SCCDCV_package_message\x12\r\n\x05\x61_no2\x18\x01 \x01(\x02\x12\r\n\x05\x61_ufp\x18\x02 \x01(\x02\x12\x0c\n\x04\x61_bc\x18\x03 \x01(\x02\x12\r\n\x05n_no2\x18\x04 \x01(\x02\x12\r\n\x05n_ufp\x18\x05 \x01(\x02\x12\x0c\n\x04n_bc\x18\x06 \x01(\x02\x12\r\n\x05v_no2\x18\x07 \x01(\x02\x12\r\n\x05v_ufp\x18\x08 \x01(\x02\x12\x0c\n\x04v_bc\x18\t \x01(\x02\x12\x12\n\nn_core_no2\x18\n \x01(\x02\x12\x12\n\nn_core_ufp\x18\x0b \x01(\x02\x12\x11\n\tn_core_bc\x18\x0c \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.ASCCDCV_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASCCDCV_PACKAGE_MESSAGE']._serialized_start=50
  _globals['_ASCCDCV_PACKAGE_MESSAGE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
