# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/IOT10_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/IOT10_package.proto\x12\rIOT10_package\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n\x15IOT10_package_message\x12\x12\n\ncreated_at\x18\x01 \x01(\t\x12\x10\n\x08\x65ntry_id\x18\x02 \x01(\x03\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x11\n\tturbidity\x18\x04 \x01(\x03\x12\x17\n\x0f\x64isolved_oxygen\x18\x05 \x01(\x02\x12\n\n\x02ph\x18\x06 \x01(\x02\x12\x0f\n\x07\x61mmonia\x18\x07 \x01(\x02\x12\x0f\n\x07nitrate\x18\x08 \x01(\x03\x12\x12\n\npopulation\x18\t \x01(\x03\x12\x0e\n\x06length\x18\n \x01(\x02\x12\x0e\n\x06weight\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.IOT10_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IOT10_PACKAGE_MESSAGE']._serialized_start=79
  _globals['_IOT10_PACKAGE_MESSAGE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
