# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/IOT2_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/IOT2_package.proto\x12\x0cIOT2_package\"\xfe\x01\n\x14IOT2_package_message\x12\x12\n\ncreated_at\x18\x01 \x01(\t\x12\x10\n\x08\x65ntry_id\x18\x02 \x01(\x03\x12\x15\n\rtemperature_c\x18\x03 \x01(\x02\x12\x15\n\rturbidity_ntu\x18\x04 \x01(\x03\x12\x1b\n\x13\x64issolved_oxygengml\x18\x05 \x01(\x02\x12\n\n\x02ph\x18\x06 \x01(\x02\x12\x12\n\nammoniagml\x18\x07 \x01(\x02\x12\x12\n\nnitrategml\x18\x08 \x01(\x03\x12\x12\n\npopulation\x18\t \x01(\x03\x12\x16\n\x0e\x66ish_length_cm\x18\n \x01(\x02\x12\x15\n\rfish_weight_g\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.IOT2_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IOT2_PACKAGE_MESSAGE']._serialized_start=44
  _globals['_IOT2_PACKAGE_MESSAGE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
