# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/IOT8_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/IOT8_package.proto\x12\x0cIOT8_package\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n\x14IOT8_package_message\x12.\n\ncreated_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08\x65ntry_id\x18\x03 \x01(\x03\x12\x15\n\rtemperature_c\x18\x04 \x01(\x02\x12\x14\n\x0cturbidityntu\x18\x05 \x01(\x03\x12\x1c\n\x14\x64issolved_oxygen_mgl\x18\x06 \x01(\x02\x12\n\n\x02ph\x18\x07 \x01(\x02\x12\x13\n\x0b\x61mmonia_mgl\x18\x08 \x01(\x02\x12\x13\n\x0bnitrate_mgl\x18\t \x01(\x03\x12\x17\n\x0ftotal_length_cm\x18\n \x01(\x02\x12\x10\n\x08weight_g\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.IOT8_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IOT8_PACKAGE_MESSAGE']._serialized_start=77
  _globals['_IOT8_PACKAGE_MESSAGE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
