# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/IOTNL_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/IOTNL_package.proto\x12\rIOTNL_package\"\x89\x02\n\x15IOTNL_package_message\x12\x13\n\x0b\x66ramenumber\x18\x01 \x01(\x03\x12\x11\n\tframetime\x18\x02 \x01(\x03\x12\x10\n\x08\x66ramelen\x18\x03 \x01(\x03\x12\x0e\n\x06\x65thsrc\x18\x04 \x01(\x03\x12\x0e\n\x06\x65thdst\x18\x05 \x01(\x03\x12\r\n\x05ipsrc\x18\x06 \x01(\x03\x12\r\n\x05ipdst\x18\x07 \x01(\x03\x12\x0f\n\x07ipproto\x18\x08 \x01(\x03\x12\r\n\x05iplen\x18\t \x01(\x02\x12\x0e\n\x06tcplen\x18\n \x01(\x02\x12\x12\n\ntcpsrcport\x18\x0b \x01(\x02\x12\x12\n\ntcpdstport\x18\x0c \x01(\x03\x12\r\n\x05value\x18\r \x01(\x02\x12\x11\n\tnormality\x18\x0e \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.IOTNL_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IOTNL_PACKAGE_MESSAGE']._serialized_start=46
  _globals['_IOTNL_PACKAGE_MESSAGE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
