# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/IOTTEMP_package.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/IOTTEMP_package.proto\x12\x0fIOTTEMP_package\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\x17IOTTEMP_package_message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\troom_idid\x18\x02 \x01(\t\x12.\n\nnoted_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04temp\x18\x04 \x01(\x03\x12\r\n\x05outin\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.IOTTEMP_package_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IOTTEMP_PACKAGE_MESSAGE']._serialized_start=83
  _globals['_IOTTEMP_PACKAGE_MESSAGE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
