# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/m_beach.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/m_beach.proto\x12\x07m_beach\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x03\n\x0fm_beach_message\x12\x14\n\x0cStation_Name\x18\x01 \x01(\t\x12\x39\n\x15Measurement_Timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0f\x41ir_Temperature\x18\x03 \x01(\x02\x12\x1c\n\x14Wet_Bulb_Temperature\x18\x04 \x01(\x02\x12\x10\n\x08Humidity\x18\x05 \x01(\x03\x12\x16\n\x0eRain_Intensity\x18\x06 \x01(\x02\x12\x15\n\rInterval_Rain\x18\x07 \x01(\x02\x12\x12\n\nTotal_Rain\x18\x08 \x01(\x02\x12\x1a\n\x12Precipitation_Type\x18\t \x01(\x03\x12\x16\n\x0eWind_Direction\x18\n \x01(\x03\x12\x12\n\nWind_Speed\x18\x0b \x01(\x02\x12\x1a\n\x12Maximum_Wind_Speed\x18\x0c \x01(\x02\x12\x1b\n\x13\x42\x61rometric_Pressure\x18\r \x01(\x02\x12\x17\n\x0fSolar_Radiation\x18\x0e \x01(\x03\x12\x0f\n\x07Heading\x18\x0f \x01(\x03\x12\x14\n\x0c\x42\x61ttery_Life\x18\x10 \x01(\x02\x12#\n\x1bMeasurement_Timestamp_Label\x18\x11 \x01(\t\x12\x16\n\x0eMeasurement_ID\x18\x12 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.m_beach_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_M_BEACH_MESSAGE']._serialized_start=67
  _globals['_M_BEACH_MESSAGE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
