# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package_compressed_no_descriptors.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n'package_compressed_no_descriptors.proto\"N\n\x11\x43ompressedMessage\x12\x11\n\tstruct_id\x18\x01 \x03(\x05\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x15\n\rmessage_sizes\x18\x03 \x03(\x05\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "package_compressed_no_descriptors_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_COMPRESSEDMESSAGE"]._serialized_start = 43
    _globals["_COMPRESSEDMESSAGE"]._serialized_end = 121
# @@protoc_insertion_point(module_scope)
