# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package_compressed.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18package_compressed.proto"{\n\x1fSelfDescribingCompressedMessage\x12\x16\n\x0e\x64\x65scriptor_set\x18\x01 \x01(\x0c\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x18\n\x10\x64\x65scriptor_sizes\x18\x03 \x03(\x05\x12\x15\n\rmessage_sizes\x18\x04 \x03(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "package_compressed_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SELFDESCRIBINGCOMPRESSEDMESSAGE"]._serialized_start = 28
    _globals["_SELFDESCRIBINGCOMPRESSEDMESSAGE"]._serialized_end = 151
# @@protoc_insertion_point(module_scope)
